WP/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name="WP"


urlpatterns = [

    path('admin/', admin.site.urls,name="admin"),
    path('',views.index,name="index"),
    path('login/',views.login,name="login"),
    path('logout/',views.logout_user,name="logout"),
    path('CreateWaterPlant/',views.CreateWaterPlant,name="CreateWaterPlant"),
    path('CreateWaterPlantLoc/',views.CreateWaterPlantLoc,name="CreateWaterPlantLoc"),
    path('WaterPlantLocDB/',views.WaterPlantLocDB,name="WaterPlantLocDB"),
    path('SetWarrentyDate/',views.SetWarrentyDate,name="SetWarrentyDate"),
    path('WaterPlantLocUpdate/<int:pk>/',views.WaterPlantLocUpdate,name="WaterPlantLocUpdate"),
    path('WaterPlantLocDelete/<int:pk>/',views.WaterPlantLocDelete,name="WaterPlantLocDelete"),
    path('CreateWaterPlantLocViaImport/',views.CreateWaterPlantLocViaImport,name="CreateWaterPlantLocViaImport"),
    path('ajax/load-mandal/',views.load_mandal,name='ajax_load_mandal'),
    path('ajax/load-gram_panchayat/',views.load_gram_panchayat,name='ajax_load_gram_panchayat'),
    path('ajax/load-village/',views.load_village,name='ajax_load_village'),
    path('ajax/load-constency/',views.load_constency,name='ajax_load_constency'),
    path('WaterPlantsDB/New/',views.view_new_water_plants,name='list-of-new-water-plants'),
    path('WaterPlantsDB/AMC/',views.view_amc_water_plants,name='list-of-amc-water-plants'),
    path('WaterPlantUpdate/<int:pk>/',views.WaterPlantUpdate,name="WaterPlantUpdate"),
    path('WaterPlantUpdateForm/<int:pk>/',views.UpdateWaterPlant_form,name="WaterPlantUpdate-form"),
    path('WaterPlantDelete/<int:pk>/',views.WaterPlantDelete,name="WaterPlantDelete"),
    path('ajax_new_filtertable/',views.ajax_filtertable_new,name='filter-ajax'),
    path('ajax_old_filtertable/',views.ajax_filtertable_old,name='filter-old-ajax'),
    path('AddConsumables/',views.AddConsumbles,name='AddConsumbles'),
    path('CostManagemnt/',views.cost_management,name="cost-management"),
    path('ajax_get_wp_name/',views.ajax_get_wp_name,name='ajax_get_wp_name'),
    path('ajax/load-mandal/wp',views.load_mandal_wp,name='ajax_load_mandal_wp'),
    path('ajax/load-gram_panchayat/wp',views.load_gram_panchayat_wp,name='ajax_load_gram_panchayat_wp'),
    path('ajax/load-village/wp',views.load_village_wp,name='ajax_load_village_wp'),
    path('ajax/load-constency/wp',views.load_constency_wp,name='ajax_load_constency_wp'),
    path('consumablesDB/',views.consumables_list,name="consumables_list"),
    path('table_consumable_list/',views.table_consumable_list,name="table_consumable_list"),
    path('consumables/delete/<int:pk>',views.ConsumablesDelete,name='ConsumablesDelete'),
    path('cost/delete/<int:pk>',views.deleteCost,name='CostDelete'),
    path('AddRepairParts/',views.AddRepairParts,name='AddRepairParts'),
    path('RepairPartsDB/',views.RepairPartsDB,name='RepairPartsDB'),
    path('AjaxRepairPartsBB/',views.table_repair_parts_data,name='table_repair_parts_data'),
    path('deleteRepairParts/<int:pk>',views.deleteRepairParts,name='deleteRepairParts'),
    path('consumable_track/',views.view_consumable_track,name='consumable_track'),
    path('ajax/get_years/',views.get_years,name='get_years'),
    path('ajax_view_consumable_track/',views.ajax_view_consumable_track,name='ajax_view_consumable_track'),
    path('ajax_view_consumable_track_yearly/',views.view_consumable_track_yearly,name='view_consumable_track_yearly'), 
    path('financial_track/',views.view_financial_track,name='financial_track'),
    path('ajax_view_financial_track/',views.ajax_view_financial_track,name='ajax_view_financial_track'),
    path('ajax_view_financial_track_yearly/',views.view_financial_track_yearly,name='view_financial_track_yearly'), 
    path('monthly_consumable_bar_gph/',views.monthly_consumable_bar_gph,name='monthly_consumable_bar_gph'),
    path('get_water_plants/',views.get_water_plants,name='get_water_plants'),
    path('monthly_bar_graph/',views.monthly_bar_graph,name='monthly_bar_graph'),
    path('monthly_financial_bar_gph/',views.monthly_financial_bar_gph,name='monthly_financial_bar_gph'),
    path('monthly_bar_graph_f/',views.monthly_bar_graph_f,name='monthly_bar_graph_f'),
    path('cost_management_graph/',views.cost_management_graph,name='cost_management_graph'),
    path('complete_water_plant_report/<int:pk>',views.complete_water_plant_report,name='complete_water_plant_report'),
    path('water_plant_import/',views.water_plant_import,name='water-plant-import'),
    path('sample_download/',views.sample_download,name='sample_download'),
    path('wpnew/export/',views.wpnew_export,name='wpnew-export'),
    path('wpamc/export/',views.wpamc_export,name='wpamc-export'),
    path('DetailFinancialReport/<int:pk>',views.detailed_FP,name='detailed_FP'),
    path('complete_financial_report/',views.complete_financial_report,name='complete_financial_report'),
    path('ReportGenerator/',views.ReportGenerator,name='ReportGenerator'),
    path('Notifications/',views.NotificationManager,name='notifications'),
    path('AddConsumables_withpk/<int:pk>',views.AddConsumables_withpk,name='AddConsumables_withpk'),
    path('AddConsumblesPK/<int:pk>',views.AddConsumblesPK,name='AddConsumblesPK'),
    path('ReportPage/',views.ReportPage,name='ReportPage'),
    path('SettingsPage/',views.SettingPage,name='SettingPage'),
    path('WaterPlantPage/',views.WPPage,name='WaterPlantPage'),
    path('Incharge/Add/',views.InchargeCreateView.as_view(),name='CreateIncharge'),
]

WPDMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from WP import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wp/',include('WP.urls')),
    path('login/',views.login,name="login"),
    path('',views.index,name="index"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


admin.site.site_header=("Water Plant Details Management System Administration")
admin.site.site_title=("WPDMS Admin")

WP/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser
from django.urls import reverse, reverse_lazy

# Create your models here.


class WarrentyYear(models.Model):
    year = models.IntegerField()

 # District model


class WaterPlantLoc(models.Model):
    district = models.CharField(max_length=200)
    mandal = models.CharField(max_length=200)
    gram_panchayat = models.CharField(max_length=200)
    village = models.CharField(max_length=200)
    constency = models.CharField(max_length=200)

    def __str__(self):
        return self.district+' | '+self.mandal+' | ' + self.gram_panchayat+' | '+self.village+' | '+self.constency


class User(AbstractUser):
    mob_no_regex = RegexValidator(regex='^\([0-9]{2}\)[1-9][0-9]{9}$|^[1-9][0-9]{9}$',
                                  message="Should be of 10 digits like (91)9999999999 or 9999999999")
    name = models.CharField(max_length=100, verbose_name='Incharge Name')
    number = models.CharField(max_length=10)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse_lazy('WP:CreateWaterPlant')


TYPE_CHOICES = (
    ('Foundation', 'FOUNDATION'),
    ('MPLADS', 'MPLADS'),
)


class WaterPlant(models.Model):
    loc = models.ForeignKey(
        WaterPlantLoc, on_delete=models.CASCADE, default='0')
    populations = models.CharField(max_length=200, null=True, blank=True)
    phone_regex = RegexValidator(
        regex=r'^\d{10}$', message="Phone number should be up to 10 digits only")
    capacity = models.CharField(max_length=10, blank=True, null=True)
    date = models.DateField()
    contact_person = models.CharField(max_length=200)
    contact_number = models.CharField(validators=[phone_regex], max_length=10)
    operator_name = models.CharField(max_length=200)
    operator_phone_number = models.CharField(
        validators=[phone_regex], max_length=10)
    incharge = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.DO_NOTHING)
    plant_type = models.CharField(
        choices=TYPE_CHOICES, max_length=15, null=True, blank=True)
    is_amc = models.BooleanField(default=False)

    def __str__(self):
        return self.loc.village


class Consumables(models.Model):
    WP = models.ForeignKey(WaterPlant, on_delete=models.CASCADE)
    filters = models.CharField(max_length=5)
    liquid_case = models.CharField(max_length=5)
    date = models.DateField()


class Cost(models.Model):
    filters = models.CharField(max_length=5)
    liquid = models.CharField(max_length=5)
    date = models.DateField()


class repair_parts(models.Model):
    WP = models.ForeignKey(WaterPlant, on_delete=models.CASCADE)
    parts = models.CharField(max_length=100)
    description = models.TextField(max_length=600)
    date = models.DateField()
    amount = models.CharField(max_length=10)

WP/forms.py
from django.forms import ModelForm, PasswordInput,HiddenInput
from django.contrib.auth.forms import UserCreationForm
from .models import WaterPlantLoc,WaterPlant,User

class WaterPlantLocForm(ModelForm):

    class Meta:
        model=WaterPlantLoc
        fields=['district','mandal','gram_panchayat','village','constency']


class InchargeForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name','username', 'first_name', 'last_name', 'password1', 'password2','number']
        widgets ={ 'name': HiddenInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = False
        
    def clean(self):
        self.cleaned_data = super().clean()
        self.cleaned_data['name'] = self.cleaned_data['first_name'] +' '+ self.cleaned_data['last_name']
        return self.cleaned_data

WP/templates/AddConsumables_withPk.html
{% extends 'base.html' %}
{% block body %}
<div id="page-wrapper">


<div class="row">
<div class="col-lg-6">
<h1 style="color:#3070a5"class="page-header"><i class="fa fa-plus"></i>  Add Consumables &nbsp;&nbsp;<a href="{% url 'WP:consumables_list'%}"<button type="button" class="btn  btn-primary"><i class="fa fa-database"></i>  Consumables Datadase</button></a></h1> 
</div>
<div class="col-lg-6">
 <h1 class="page-header" style="color:#3070a5"  >Plant Name:{{wp}}<span id="ajax-plant-name"></span></h1>
</div>
</div>

            <div class="row">
            <form role="form" method="POST" action="{% url 'WP:AddConsumblesPK' wp.pk %}">
            {% csrf_token %}
            <div class="col-lg-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4><i class="fa  fa-cube "></i>   Water Plant </h4>
                    </div>
                    <div class="panel-body">
                    {% if error_message %}
                                <div class="alert alert-danger">
                                <ul>
                                {% for i in error_message%}
                                <li><strong>{{ i }}</strong></li>
                                {% endfor %}
                                </ul>
                                </div>
                                {% endif %}
                                {% if success_message %}
                                <div class="alert alert-success">
                                <ul>
                                {% for i in success_message%}
                                <li><strong>{{ i }}</strong></li>
                                {% endfor %}
                                </ul>
                                </div>
                                {% endif %}
                    
                    
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label>District</label>
                                    <p name="district" id="id_district" class="form-control" disabled>{{wp.loc.district}}</p>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label>Mandal</label>
                                    <p name="mandal" id="id_mandal" class="form-control" disabled>{{wp.loc.mandal}}</p>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label>Gram Panchayat</label>
                                    <p name="gram_panchayat" id="id_gram_panchayat" class="form-control"  disabled>{{wp.loc.gram_panchayat}}</p>
                            </div>
                        </div>
                        <div class="col-lg-3">
                        <div class="form-group">
                                <label>Village</label>
                                    <p name="village" id="id_village" class="form-control" disabled>{{wp.loc.village}}</p>
                            </div>

                        </div>
                        <div class="col-lg-2">
                            <div class="form-group">
                                <label>Constency</label>
                                    <p name="constency" id="id_constency" class="form-control" disabled>{{wp.loc.constency}}</p>
                                
                            </div>
                        </div>
                        
                     </div>
                </div>
              </div>
               
            </div>
            <div class="row">
            <div class="col-lg-6">
            <!-- Consumable form lies here-->
            <div class="panel panel-primary">
                <div class="panel-heading">
                           <i class="fa fa-keyboard-o " ></i> Enter the quantities
                        </div>
                <div class="panel-body">
            <div class="form-group">
                    <label>Filters</label>
                        <input class="form-control"  id="id_filters" name="filters" required>
                        <p class="help-block">Example: Enter the number of Consumables.</p>
            </div>
            <div class="form-group">
                    <label>liquid Case</label>
                        <input class="form-control"  id="id_liquid_case" name="liquid_case" required>
                        <p class="help-block">Example: Enter the number of liquid cases.</p>
            </div>
            <div class="form-group">
                    <label>Date of Establishment</label>
                        <input class="form-control" type="date" id="id_date" name="date" required>
                        <p class="help-block">Example: Date of Establishment.</p>
            </div>
             <button type="submit" class="btn btn-success">Submit</button>
                     &nbsp;&nbsp;
                    <a href="#"><button type="button" class="btn btn-primary">Reset</button></a>
            </div>
            </div>
            </div>
            </form>
                        
            </div>
            </div>

           
                    
                       
          

             
</div>

<script>
      $("#id_district").change(function(){
       
      var url = $("#WaterPlantForm").attr("data-user-url");  // get the url of the `load_cities` view
      var district = $("#id_district").val();  // get the selected country ID from the HTML input
      console.log(district)
      $.ajax({                       // initialize an AJAX request
        url: "{% url 'WP:ajax_load_mandal_wp'%}",                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'district': district       // add the country id to the GET parameters
        },
        success: function (data) {
             // `data` is the return of the `load_cities` view function
            
          $("#id_mandal").html(data);
            // replace the contents of the city input with the data that came from the server
        }
      });
    });
  </script>

  <script>
      $("#id_mandal").change(function(){
       
      var url = $("#WaterPlantForm").attr("data-user-url");  // get the url of the `load_cities` view
      var mandal = $("#id_mandal").val();  // get the selected country ID from the HTML input
      console.log(mandal)
      $.ajax({                       // initialize an AJAX request
        url: "{% url 'WP:ajax_load_gram_panchayat_wp'%}",                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'mandal': mandal       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_gram_panchayat").html(data);
            // replace the contents of the city input with the data that came from the server
        }
      });
    });
  </script>

  <script>
      $("#id_gram_panchayat").change(function(){
       
      var url = $("#WaterPlantForm").attr("data-user-url");  // get the url of the `load_cities` view
      var gram_panchayat = $("#id_gram_panchayat").val();  // get the selected country ID from the HTML input
      console.log(gram_panchayat)
      $.ajax({                       // initialize an AJAX request
        url: "{% url 'WP:ajax_load_village_wp'%}",                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'gram_panchayat': gram_panchayat       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_village").html(data);
            // replace the contents of the city input with the data that came from the server
        }
      });
    });
  </script>


<script>
      $("#id_village").change(function(){
       
      var url = $("#WaterPlantForm").attr("data-user-url");  // get the url of the `load_cities` view
      var village = $("#id_village").val();  // get the selected country ID from the HTML input
      $.ajax({                       // initialize an AJAX request
        url: "{% url 'WP:ajax_load_constency_wp'%}",                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'village': village       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_constency").html(data);
            // replace the contents of the city input with the data that came from the server
        }
      });
    });
  </script>

<script>
      $("#id_district,#id_mandal,#id_gram_panchayat,#id_village,#id_constency").change(function(){
       
      var url = $("#WaterPlantForm").attr("data-user-url");  // get the url of the `load_cities` view
      var gram_panchayat=$("#id_gram_panchayat").val();
      var constency=$("#id_constency").val();
      var district=$("#id_district").val();
      var mandal=$("#id_mandal").val();
      var village = $("#id_village").val();
      if(village!="NULL" && gram_panchayat!="NULL" && constency!="NULL" && mandal!="NULL" && district!="NULL")
      {
      $.ajax({                       // initialize an AJAX request
        url: "{% url 'WP:ajax_get_wp_name'%}",                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'village': village,
          'mandal': mandal,
          'gram_panchayat':gram_panchayat,
          'district':district,
          'constency':constency       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#ajax-plant-name").html(data);
            // replace the contents of the city input with the data that came from the server
        }
      });
      }
      else
      {
          $("#ajax-plant-name").html(data)="NaN"
      }
     
    });

</script>





  <script>
$(function() {
    Morris.Bar({
        element: 'morris-bar-chart',
        data: [{
            y: '2006',
            a: 100,
            b: 90
        }, {
            y: '2007',
            a: 75,
            b: 65
        }, {
            y: '2008',
            a: 50,
            b: 40
        }, {
            y: '2009',
            a: 75,
            b: 65
        }, {
            y: '2010',
            a: 50,
            b: 40
        }, {
            y: '2011',
            a: 75,
            b: 65
        }, {
            y: '2012',
            a: 100,
            b: 90
        },{
            y: '2009',
            a: 75,
            b: 65
        }, {
            y: '2010',
            a: 50,
            b: 40
        }, {
            y: '2011',
            a: 75,
            b: 65
        }, {
            y: '2012',
            a: 100,
            b: 90
        }],
        xkey: 'y',
        ykeys: ['a', 'b'],
        labels: ['Series A', 'Series B'],
        hideHover: 'auto',
        resize: true
    });
});

</script>

{% endblock %}

WP/templates/ajax_get_wp_name.html
{{data}}

WP/templates/ajax_new_table.html
{% for i in data %}
    <tr class="odd gradeX">
            <td><a href="{% url 'WP:WaterPlantUpdate' i.pk %}"><i class="fa fa fa-eye"></i></a>&nbsp;<a href="{% url 'WP:WaterPlantDelete' i.pk %}"><i class="fa fa fa-times-circle-o"></i></a></td>
                    <td>{{i.loc.district}}</td>
                 <td>{{i.loc.mandal}}</td>
                    <td>{{i.loc.gram_panchayat}}</td>
                                        <td>{{i.loc.village }}</td>
                                        <td>{{i.loc.constency}}</td>
                                        <td>{{i.populations}}</td>
                                        <td>{{i.capacity}}</td>
                                        <td>{{i.date}}</td>
                                    </tr>
                                {%endfor%}

WP/templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% load staticfiles %}

  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Water Plant Details Management S" />
    <meta name="author" content="Shashwat Sanket" />

    <title>WPDMS</title>
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'favicon1.ico' %}"
    />

    <!-- Bootstrap Core CSS -->
    <link
      href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />

    <!-- MetisMenu CSS -->
    <link
      href="{% static 'vendor/metisMenu/metisMenu.min.css' %}"
      rel="stylesheet"
    />

    <!-- Custom CSS -->
    <link href="{% static 'dist/css/sb-admin-2.css' %}" rel="stylesheet" />

    <!-- Morris Charts CSS -->
    <link href="{% static 'vendor/morrisjs/morris.css' %}" rel="stylesheet" />

    <!-- Custom Fonts -->
    <link
      href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
      img {
        margin-top: 25px;
        margin-bottom: 10px;
      }
      a:hover {
        background-color: #337ab7;
      }
    </style>
  </head>

  <body>
    <div id="wrapper">
      <!-- Navigation -->
      <nav
        class="navbar navbar-default navbar-static-top"
        role="navigation"
        style="margin-bottom: 0;background-color:#337AB7"
      >
        <div class="navbar-header">
          <button
            type="button"
            class="navbar-toggle"
            data-toggle="collapse"
            data-target=".navbar-collapse"
          >
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'WP:index' %}">
            <span style="color: white;font-size: 30px;"
              >Amrutha Dhara Water Plant Management System</span
            >
          </a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
          <li class="dropdown">
            <a
              class="dropdown-toggle"
              data-toggle="dropdown"
              href="{% url 'WP:SettingPage'%}"
            >
              <h4 style="color:white">
                <i class="fa fa-cogs fa-fw" style="color:white;"></i> Settings
              </h4>
            </a>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" href="{% url 'WP:logout'%}">
              <h4 style="color:white">
                <i class="fa fa-sign-out fa-fw" style="color:white;"></i>Log Out
              </h4>
            </a>
          </li>
        </ul>
        <!-- /.navbar-top-links -->
        <div
          class="navbar-default sidebar"
          id="clpse"
          role="navigation"
          style="font-size:17px"
        >
          <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
              <li>
                <center>
                  <img
                    src="{% static 'ii.png' %}"
                    alt="USER AVTAR"
                    height="75"
                    width="75"
                  />
                </center>
              </li>
              <li>
                <a href="{% url 'WP:index' %}"
                  ><i class="fa fa-dashboard fa-fw"></i> Dashboard</a
                >
              </li>
              {% if request.user.is_superuser %}
              <li>
                <a href="#"
                  ><i class="fa fa-cubes fa-fw"></i> Water Plant<span
                    class="fa arrow"
                  ></span
                ></a>
                <ul class="nav nav-second-level">
                  <li>
                    <a href="{% url 'WP:CreateWaterPlant' %}"
                      >Create New Water Plant</a
                    >
                  </li>
                  <li>
                    <a href="#"
                      >Water Plant Database<span class="fa arrow"></span
                    ></a>
                    <ul class="nav nav-third-level">
                      <li>
                        <a href="{% url 'WP:list-of-new-water-plants' %}">
                          New Water Plants Database</a
                        >
                      </li>
                      <li>
                        <a href="{% url 'WP:list-of-amc-water-plants' %}"
                          >AMC Water Plants Database</a
                        >
                      </li>
                    </ul>
                  </li>
                </ul>
                <!-- /.nav-second-level -->
              </li>
              {% endif %}
              <li>
                <a href="{% url 'WP:AddConsumbles' %}"
                  ><i class="fa fa-edit fa-fw"></i> Add Consumables
                </a>
              </li>
              {% if request.user.is_superuser %}
              <li>
                <a href="{% url 'WP:cost-management' %}"
                  ><i class="fa fa-inr fa-fw"></i> Cost Management</a
                >
              </li>
              {% endif %}
              <li>
                <a href="{% url 'WP:AddRepairParts' %}"
                  ><i class="fa fa-wrench fa-fw"></i> Repair Parts</a
                >
                <!-- /.nav-second-level -->
              </li>
              {% if request.user.is_superuser %}
              <li>
                <a href="#"
                  ><i class="fa fa-line-chart fa-fw"></i> Reports Analysis<span
                    class="fa arrow"
                  ></span
                ></a>
                <ul class="nav nav-second-level">
                  <li>
                    <a href="{% url 'WP:ReportGenerator' %}"
                      >Complete Report Generator</a
                    >
                  </li>
                  <li>
                    <a href="{% url 'WP:consumable_track' %}"
                      >Consumable Track</a
                    >
                  </li>
                  <li>
                    <a href="{% url 'WP:financial_track' %}"
                      >Financial Report</a
                    >
                  </li>
                </ul>
                <!-- /.nav-second-level -->
              </li>
              {% endif %} {% if request.user.is_superuser %}
              <li>
                <a href="#"
                  ><i class=" 	fa fa-cogs fa-fw"></i> Settings<span
                    class="fa arrow"
                  ></span
                ></a>
                <ul class="nav nav-second-level">
                  <li>
                    <a href="{% url 'WP:SetWarrentyDate' %}">Warrent Year</a>
                  </li>
                  <li>
                    <a href="{% url 'WP:CreateWaterPlantLoc' %}"
                      >Predefined Data
                    </a>
                  </li>
                  <li>
                    <a href="{% url 'WP:WaterPlantLocDB' %}"
                      >Predefined Data Databse</a
                    >
                  </li>
                </ul>
                <!-- /.nav-second-level -->
              </li>
              {% endif %}
            </ul>
          </div>
          <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
      </nav>
    </div>
    <!-- /#wrapper -->

    <!-- /sortform-->
    <script>
      window.onresize = function() {
        var w = (document.getElementById("ti").innerHTML = "WPDMS");
      };
    </script>
    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'vendor/metisMenu/metisMenu.min.js' %}"></script>

    <!-- Morris Charts JavaScript -->
    <script src="{% static 'vendor/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'vendor/morrisjs/morris.min.js' %}"></script>
    <script src="{% static 'data/morris-data.js' %}"></script>

    <script src="{% static 'vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables-plugins/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/datatables-responsive/dataTables.responsive.js' %}"></script>
    <!-- Custom Theme JavaScript -->
    <script src="{% static 'dist/js/sb-admin-2.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/myjs.js' %}"></script>

    {% block body %} {% endblock %}
  </body>
</html>